language: java

node_js:
  - "4"

jdk:
  - oraclejdk8

before_install:
- sudo apt-get update -qq

install:
- curl -s -S -O http://haxe.org/website-content/downloads/3.2.1/downloads/haxe-3.2.1-linux64.tar.gz
- tar xzf haxe-3.2.1-linux64.tar.gz
- mvn clean --settings settings.xml
- curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
- sudo apt-get install -y nodejs
- nvm install 4 || true
- nvm use 4 || true

before_script:
- export HAXE_STD_PATH=$PWD/haxe-3.2.1/std
- export HAXEPATH=$PWD/haxe-3.2.1
- export PATH=$HAXEPATH:$PATH
- ls -la $PWD
- ls -la $PWD/haxe-3.2.1
- java -version || true
- haxe -version || true
- node --version || true
- nodejs --version || true
- nvm --version || true
- which haxe || true
- which node || true
- which nodejs || true
- which java || true
- which nvm || true
- mvn install -f jtransc-rt-core/pom.xml
- mvn install -f jtransc-rt/pom.xml

script:
- mvn install --settings settings.xml
