language: java

node_js:
  - "4"

jdk:
  - oraclejdk8

before_install:
- sudo apt-get update -qq

install:
- sudo add-apt-repository ppa:ondrej/php -y
- sudo apt-get -y update
- sudo apt-get -y install php7.0
- mvn clean --settings settings.xml
- nvm install 4 || true
- nvm use 4 || true

before_script:
- ls -la $PWD
- which java || true
- java -version || true
- which nvm || true
- nvm --version || true
- which node || true
- node --version || true
- php --version || true

script:
- mvn install --settings settings.xml
